### ISSUE TITLE
Rename repo to flutter_callkeep

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/callkeep#10]
I'm doing this and it's failing due to name:

```
dependency_overrides:
  # https://dart.dev/tools/pub/dependencies#git-packages
  sip_ua:
    git: git@github.com:cloudwebrtc/dart-sip-ua.git
  flutter_callkeep:
    git: git@github.com:flutter-webrtc/callkeep.git
```

and `pub get` fails:

```
Running "flutter pub get" in SureVoIP-Talk...                   
Error on line 1, column 7: "name" field doesn't match expected name "flutter_callkeep".

  ╷

1 │ name: callkeep

  │       ^^^^^^^^

  ╵
pub get failed (65;   ╵)
Process finished with exit code 65
```
