### ISSUE TITLE
Is the plugin still active and is being maintained?

### ISSUE THREAD

**Issue by yassinsameh** [flutter-webrtc/callkeep#139]
Hi, though i've seen many unanswered issues and some being there since many months, i have however seen a commit being pushed a month ago, so i wonder if you can clarify if the project is still being maintained. We'd love to use this plugin but it wouldn't make sense if it isn't, hope someone can clarify, thank you. @hiroshihorie @ycherniavskyi @efraespada @shomatan @cloudwebrtc

**Comment by efraespada** [comment]
I use and contribute to this plugin. Be patient.

Feel free for forking and doing any change you consider.

You can use your branch until it is merged (opening a PR of course):

```yml
  callkeep:                                     # android   ios
    git:
      url: https://github.com/efraespada/callkeep.git

```
